//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng4You.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eng4You.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+972) 0512532477.
        /// </summary>
        public static string @__972__0512532477 {
            get {
                return ResourceManager.GetString("(+972) 0512532477", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a responsible for the software department.
        /// </summary>
        public static string @__who_is_the_responsible_for_the_software_department {
            get {
                return ResourceManager.GetString(", who is the responsible for the software department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/24.
        /// </summary>
        public static string _24_24 {
            get {
                return ResourceManager.GetString("24/24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8:00PM.
        /// </summary>
        public static string _5_00PM {
            get {
                return ResourceManager.GetString("5:00PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:00AM.
        /// </summary>
        public static string _9_00AM {
            get {
                return ResourceManager.GetString("9:00AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95.
        /// </summary>
        public static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cyber security engineer, who is responsible for the security department in.
        /// </summary>
        public static string A_cyber_security_engineer__who_is_the_responsible_for_the_security_department {
            get {
                return ResourceManager.GetString("A cyber security engineer, who is the responsible for the security department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,a manager of its software department.
        /// </summary>
        public static string a_manager_of_its_software_department_ {
            get {
                return ResourceManager.GetString("a manager of its software department.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdallah Abuali,.
        /// </summary>
        public static string Abdallah_Abuali_ {
            get {
                return ResourceManager.GetString("Abdallah Abuali,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A New Section.
        /// </summary>
        public static string Add_A_New_Section {
            get {
                return ResourceManager.GetString("Add A New Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Section.
        /// </summary>
        public static string Add_Section {
            get {
                return ResourceManager.GetString("Add Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative assistant at.
        /// </summary>
        public static string Administrative_assistant_in {
            get {
                return ResourceManager.GetString("Administrative assistant in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        public static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and discovering security vulnerabilities in everything related for it is.
        /// </summary>
        public static string and_discovering_security_vulnerabilities_in_everything_related_to {
            get {
                return ResourceManager.GetString("and discovering security vulnerabilities in everything related to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture Engineering.
        /// </summary>
        public static string Architecture_Engineering {
            get {
                return ResourceManager.GetString("Architecture Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are We.
        /// </summary>
        public static string Are_We {
            get {
                return ResourceManager.GetString("Are We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aya AL_Awesat,.
        /// </summary>
        public static string Aya_AL_Awesat_ {
            get {
                return ResourceManager.GetString("Aya AL_Awesat,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss and owner of.
        /// </summary>
        public static string Boss_and_owner_of {
            get {
                return ResourceManager.GetString("Boss and owner of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bshar Awad,.
        /// </summary>
        public static string Bshar_Awad_ {
            get {
                return ResourceManager.GetString("Bshar Awad,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string Call_Us {
            get {
                return ResourceManager.GetString("Call Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Engineering.
        /// </summary>
        public static string Cars_Engineering {
            get {
                return ResourceManager.GetString("Cars Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Engineering.
        /// </summary>
        public static string Cars_Engineering_ {
            get {
                return ResourceManager.GetString("Cars Engineering_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Engineering.
        /// </summary>
        public static string Civil_Engineering {
            get {
                return ResourceManager.GetString("Civil Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Engineering.
        /// </summary>
        public static string Computer_Engineering {
            get {
                return ResourceManager.GetString("Computer Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete Section.
        /// </summary>
        public static string Confirm_Delete_Section {
            get {
                return ResourceManager.GetString("Confirm Delete Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_home {
            get {
                return ResourceManager.GetString("Contact home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us....
        /// </summary>
        public static string Contact_Us___ {
            get {
                return ResourceManager.GetString("Contact Us...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us through:.
        /// </summary>
        public static string Contact_us_through_ {
            get {
                return ResourceManager.GetString("Contact us through:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us to help you....
        /// </summary>
        public static string Contact_us_to_help_you___ {
            get {
                return ResourceManager.GetString("Contact us to help you...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copyright.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRIES EXPERIENCE.
        /// </summary>
        public static string COUNTRIES_EXPERIENCE {
            get {
                return ResourceManager.GetString("COUNTRIES EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        public static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Security.
        /// </summary>
        public static string Cyber_Security {
            get {
                return ResourceManager.GetString("Cyber Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Section.
        /// </summary>
        public static string Delete_Section {
            get {
                return ResourceManager.GetString("Delete Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop your skills and learning in an engineering major.
        /// </summary>
        public static string Develop_your_skills_and_learning_in_an_engineering_major {
            get {
                return ResourceManager.GetString("Develop your skills and learning in an engineering major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit The Created Sectione.
        /// </summary>
        public static string Edit_Created_Sectione {
            get {
                return ResourceManager.GetString("Edit Created Sectione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string Email_Us {
            get {
                return ResourceManager.GetString("Email Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string Eng {
            get {
                return ResourceManager.GetString("Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Books.
        /// </summary>
        public static string Engineering_Books {
            get {
                return ResourceManager.GetString("Engineering Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Majors In.
        /// </summary>
        public static string Engineering_Majors_In {
            get {
                return ResourceManager.GetString("Engineering Majors In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string Engr {
            get {
                return ResourceManager.GetString("Engr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for with us.
        /// </summary>
        public static string for__ {
            get {
                return ResourceManager.GetString("for__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For All Majors.
        /// </summary>
        public static string For_All_Majors {
            get {
                return ResourceManager.GetString("For All Majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free.
        /// </summary>
        public static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOURS OF WROK.
        /// </summary>
        public static string HOURS_OF_WROK {
            get {
                return ResourceManager.GetString("HOURS OF WROK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.eng4you@gmail.com.
        /// </summary>
        public static string info_eng4you_gmail_com {
            get {
                return ResourceManager.GetString("info.eng4you@gmail.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is dedicated to catering to engineers and engineering enthusiasts alike, by offering free courses across various engineering disciplines in a seamless and user-friendly manner. Moreover, our extensive book library encompasses resources covering all branches of engineering, additionally, we highlight the achievements and successes of engineers from diverse backgrounds and nationalities, fostering a rich and inclusive engineering learning environment..
        /// </summary>
        public static string is_dedicated_to_catering_to_engineers_and_engineering_enthusiasts_alike__by_offering_free_courses_across_various_engineering_disciplines_in_a_seamless_and_user_friendly_manner__Moreover__our_extensive_book_library_encompasses_resources_covering_all_branches_of_engineering__additionally__we_highlight_the_achievements_and_successes_of_engineers_from_diverse_backgrounds_and_nationalities__fostering_a_rich_and_inclusive_engineering_learning_environment_ {
            get {
                return ResourceManager.GetString(@"is dedicated to catering to engineers and engineering enthusiasts alike, by offering free courses across various engineering disciplines in a seamless and user-friendly manner. Moreover, our extensive book library encompasses resources covering all branches of engineering, additionally, we highlight the achievements and successes of engineers from diverse backgrounds and nationalities, fostering a rich and inclusive engineering learning environment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jinan Zahaika,.
        /// </summary>
        public static string Jinan_Zahaika_ {
            get {
                return ResourceManager.GetString("Jinan Zahaika,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical engineer, who is the responsible for the mechanical department.
        /// </summary>
        public static string Mechanical_engineer__who_is_the_responsible_for_the_mechanical_department {
            get {
                return ResourceManager.GetString("Mechanical engineer, who is the responsible for the mechanical department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle East, Turkiye, USA.
        /// </summary>
        public static string Middle_East__Turkiye__USA {
            get {
                return ResourceManager.GetString("Middle East, Turkiye, USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string Page_not_found {
            get {
                return ResourceManager.GetString("Page not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing courses and books in all engineering majors.
        /// </summary>
        public static string Providing_courses_and_books_in_all_engineering_majors {
            get {
                return ResourceManager.GetString("Providing courses and books in all engineering majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing engineering programmes for free.
        /// </summary>
        public static string Providing_programmes_for_free {
            get {
                return ResourceManager.GetString("Providing programmes for free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing all engineering opportunities you need for all majors.
        /// </summary>
        public static string Publishing_all_engineering_opportunities_you_need_for_all_majors {
            get {
                return ResourceManager.GetString("Publishing all engineering opportunities you need for all majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam Qarish,.
        /// </summary>
        public static string Salam_Qarish_ {
            get {
                return ResourceManager.GetString("Salam Qarish,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Image.
        /// </summary>
        public static string Section_Image {
            get {
                return ResourceManager.GetString("Section Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name In Arabic.
        /// </summary>
        public static string Section_Name_In_Arabic {
            get {
                return ResourceManager.GetString("Section Name In Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name In English.
        /// </summary>
        public static string Section_Name_In_English {
            get {
                return ResourceManager.GetString("Section Name In English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name In Turkish.
        /// </summary>
        public static string Section_Name_In_Turkish {
            get {
                return ResourceManager.GetString("Section Name In Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us a message for any questions you have!!! You will be reply from the support team as soon as you receive the message.
        /// </summary>
        public static string Send_us_a_message_for_any_questions_you_have____You_will_be_reply_from_the_support_team_as_soon_as_you_receive_the_message {
            get {
                return ResourceManager.GetString("Send us a message for any questions you have!!! You will be reply from the suppor" +
                        "t team as soon as you receive the message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Books.
        /// </summary>
        public static string Show_Books {
            get {
                return ResourceManager.GetString("Show Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineering.
        /// </summary>
        public static string Software_Engineering {
            get {
                return ResourceManager.GetString("Software Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        public static string Success_Stories {
            get {
                return ResourceManager.GetString("Success Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talking about the successes of engineers.
        /// </summary>
        public static string Talking_about_the_successes_of_engineers {
            get {
                return ResourceManager.GetString("Talking about the successes of engineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team .
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PROJECTS.
        /// </summary>
        public static string TOTAL_PROJECTS {
            get {
                return ResourceManager.GetString("TOTAL PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Image Section.
        /// </summary>
        public static string Update_Image_Section {
            get {
                return ResourceManager.GetString("Update Image Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Section Name In Arabic.
        /// </summary>
        public static string Update_Section_Name_In_Arabic {
            get {
                return ResourceManager.GetString("Update Section Name In Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Section Name In English.
        /// </summary>
        public static string Update_Section_Name_In_English {
            get {
                return ResourceManager.GetString("Update Section Name In English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Section Name In Turkish.
        /// </summary>
        public static string Update_Section_Name_In_Turkish {
            get {
                return ResourceManager.GetString("Update Section Name In Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image Section.
        /// </summary>
        public static string Upload_Image_Section {
            get {
                return ResourceManager.GetString("Upload Image Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are dedicated to catering to engineers and engineering enthusiasts a like, display life&apos;s engineering challenges in an easy and engaging manner, and providing effective solutions. For further information on our services....
        /// </summary>
        public static string We_are_dedicated_to_catering_to_engineers_and_engineering_enthusiasts_a_like__display_life_s_engineering_challenges_in_an_easy_and_engaging_manner__and_providing_effective_solutions__For_further_information_on_our_services___ {
            get {
                return ResourceManager.GetString("We are dedicated to catering to engineers and engineering enthusiasts a like, dis" +
                        "play life\'s engineering challenges in an easy and engaging manner, and providing" +
                        " effective solutions. For further information on our services...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Help To Get The Best Engineering Services For All Majors.
        /// </summary>
        public static string We_Help_To_Get_The_Best_Engineering_Services_For_All_Majors {
            get {
                return ResourceManager.GetString("We Help To Get The Best Engineering Services For All Majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Coming Soon.
        /// </summary>
        public static string We_re_Coming_Soon {
            get {
                return ResourceManager.GetString("We\'re Coming Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re working hard to give you the best experience.
        /// </summary>
        public static string We_re_working_hard_to_give_you_the_best_experience {
            get {
                return ResourceManager.GetString("We\'re working hard to give you the best experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who.
        /// </summary>
        public static string Who {
            get {
                return ResourceManager.GetString("Who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is responsible for the design and architecture department in.
        /// </summary>
        public static string Who_is_the_responsible_for_the_design_and_architecture_department_in {
            get {
                return ResourceManager.GetString("Who is the responsible for the design and architecture department in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        public static string Working_Hours {
            get {
                return ResourceManager.GetString("Working Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You_tr_aya {
            get {
                return ResourceManager.GetString("You tr aya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You_Tr_Bshar {
            get {
                return ResourceManager.GetString("You Tr Bshar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You,.
        /// </summary>
        public static string You_tr_jinan {
            get {
                return ResourceManager.GetString("You tr jinan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You_Tr_salam {
            get {
                return ResourceManager.GetString("You Tr salam", resourceCulture);
            }
        }
    }
}
